# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['@all']
   'require':
    'frameworks/extra-cmake-modules': '@stable-kf6'
    'frameworks/kcoreaddons': '@stable-kf6'
    'frameworks/kconfig': '@stable-kf6'
    'frameworks/kwidgetsaddons': '@stable-kf6'
    'frameworks/ki18n': '@stable-kf6'
    'frameworks/kio': '@stable-kf6'
    'frameworks/kcmutils': '@stable-kf6'
    'frameworks/ktextwidgets': '@stable-kf6'
    'frameworks/kxmlgui': '@stable-kf6'
    'frameworks/kservice': '@stable-kf6'
    'frameworks/kiconthemes': '@stable-kf6'
    'frameworks/karchive': '@stable-kf6'
    'frameworks/knotifications': '@stable-kf6'
    'frameworks/kstatusnotifieritem': '@stable-kf6'

Options:
 require-passing-tests-on: ['Linux', 'FreeBSD', 'Windows']
