# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/kwidgetsaddons': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kio': '@stable'
    'frameworks/kcmutils': '@stable'
    'frameworks/ktextwidgets': '@stable'
    'frameworks/kxmlgui': '@stable'
    'frameworks/kservice': '@stable'
    'frameworks/kiconthemes': '@stable'
    'frameworks/karchive': '@stable'
    'frameworks/knotifications': '@stable'

Options:
  require-passing-tests-on: ['Linux', 'FreeBSD', 'Windows']
